//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infini.AutomaticDivideTool.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infini.AutomaticDivideTool.API.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常終了.
        /// </summary>
        internal static string MSGLINX0 {
            get {
                return ResourceManager.GetString("MSGLINX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーマスタに存在しない.
        /// </summary>
        internal static string MSGLINX1 {
            get {
                return ResourceManager.GetString("MSGLINX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー名が定義されていない.
        /// </summary>
        internal static string MSGLINX1001 {
            get {
                return ResourceManager.GetString("MSGLINX1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードがパラメータに定義されていない.
        /// </summary>
        internal static string MSGLINX1002 {
            get {
                return ResourceManager.GetString("MSGLINX1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCCがパラメータに定義されていない.
        /// </summary>
        internal static string MSGLINX1003 {
            get {
                return ResourceManager.GetString("MSGLINX1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダがパラメータに定義されていない\n指定されたフォルダにLINX　PLUSがインストールされていない\nまたは見つからない.
        /// </summary>
        internal static string MSGLINX1004 {
            get {
                return ResourceManager.GetString("MSGLINX1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同時起動数がオーバーしています.
        /// </summary>
        internal static string MSGLINX1005 {
            get {
                return ResourceManager.GetString("MSGLINX1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通常系が動作しているのに、バックアップ系に接続しようとした.
        /// </summary>
        internal static string MSGLINX1008 {
            get {
                return ResourceManager.GetString("MSGLINX1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロキシの設定内容に誤りがある.
        /// </summary>
        internal static string MSGLINX1009 {
            get {
                return ResourceManager.GetString("MSGLINX1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システムエラー(ログイン状態が不明).
        /// </summary>
        internal static string MSGLINX1010 {
            get {
                return ResourceManager.GetString("MSGLINX1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインコマンド送受信中に通信エラーが発生した.
        /// </summary>
        internal static string MSGLINX1100 {
            get {
                return ResourceManager.GetString("MSGLINX1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サインインコマンド送受信中に通信エラーが発生した.
        /// </summary>
        internal static string MSGLINX1101 {
            get {
                return ResourceManager.GetString("MSGLINX1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンド送受信中に通信エラーが発生した.
        /// </summary>
        internal static string MSGLINX1102 {
            get {
                return ResourceManager.GetString("MSGLINX1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サインアウト送受信中に通信エラーが発生した.
        /// </summary>
        internal static string MSGLINX1103 {
            get {
                return ResourceManager.GetString("MSGLINX1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログアウトコマンド送受信中に通信エラーが発生した.
        /// </summary>
        internal static string MSGLINX1104 {
            get {
                return ResourceManager.GetString("MSGLINX1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二重ログイン送受信中に通信エラーが発生した.
        /// </summary>
        internal static string MSGLINX1106 {
            get {
                return ResourceManager.GetString("MSGLINX1106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード不一致.
        /// </summary>
        internal static string MSGLINX2 {
            get {
                return ResourceManager.GetString("MSGLINX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCCコード不一致.
        /// </summary>
        internal static string MSGLINX3 {
            get {
                return ResourceManager.GetString("MSGLINX3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同ユーザーIDで既にログインされている.
        /// </summary>
        internal static string MSGLINX4 {
            get {
                return ResourceManager.GetString("MSGLINX4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初期ログインなし.
        /// </summary>
        internal static string MSGLINX5 {
            get {
                return ResourceManager.GetString("MSGLINX5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サインインエラー.
        /// </summary>
        internal static string MSGLINX6 {
            get {
                return ResourceManager.GetString("MSGLINX6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サインインなし.
        /// </summary>
        internal static string MSGLINX7 {
            get {
                return ResourceManager.GetString("MSGLINX7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サインアウトエラー.
        /// </summary>
        internal static string MSGLINX8 {
            get {
                return ResourceManager.GetString("MSGLINX8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システムエラー.
        /// </summary>
        internal static string MSGLINX9 {
            get {
                return ResourceManager.GetString("MSGLINX9", resourceCulture);
            }
        }
    }
}
