package com.infini.ccahe.repository;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;

import com.infini.ccahe.entity.CCacheTask;

public interface CCacheTaskRepository extends CrudRepository<CCacheTask, Long> {
	@Query(value = "SELECT "
			+ "rq_pattern.pattern_id AS pattern_id, "
			+ "rq_pattern.departure_airport AS departure_airport, "
			+ "rq_pattern.arrival_airport AS arrival_airport, "
			+ "rq_pattern.carrier AS carrier, "
			+ "rq_pattern.outbound_date_from AS outbound_date_from, "
			+ "rq_pattern.outbound_date_to AS outbound_date_to, "
			+ "rq_pattern.outbound_date_type AS outbound_date_type, "
			+ "rq_pattern_outboundtime.`from` AS outbound_time_from, "
			+ "rq_pattern_outboundtime.`to` AS outbound_time_to, "
			+ "rq_pattern_outboundtime.`position` AS outbound_time_position, "
			+ "rq_pattern_inboundtime.`from` AS inbound_time_from, "
			+ "rq_pattern_inboundtime.`to` AS inbound_time_to, "
			+ "rq_pattern_inboundtime.`position` AS inbound_time_position, "
			+ "rq_pattern.num_of_adt AS num_of_adt, "
			+ "rq_pattern.num_of_cnn AS num_of_cnn, "
			+ "rq_pattern.num_of_ins AS num_of_ins, "
			+ "rq_pattern.num_of_inf AS num_of_inf, "
			+ "rq_pattern_staydays.stay_day AS stay_day, "
			+ "rq_pattern.stops AS stops, "
			+ "rq_pattern_cabin.cabin AS cabin, "
			+ "rq_pattern.rbd AS rbd, "
			+ "rq_pattern.exclude_codeshare AS exclude_codeshare, "
			+ "rq_pattern.free_piece AS free_piece "
			+ "FROM "
			+ "(SELECT "
			+ "rq_pattern.pattern_id AS pattern_id, "
			+ "rq_pattern.departure_airport AS departure_airport, "
			+ "rq_pattern.arrival_airport AS arrival_airport, "
			+ "rq_pattern.carrier AS carrier, "
			+ "rq_pattern.outbound_date_from AS outbound_date_from, "
			+ "CASE "
			+ "WHEN (outbound_date_to - outbound_date_from) > 180 THEN 180 "
			+ "ELSE rq_pattern.outbound_date_to "
			+ "END AS outbound_date_to, "
			+ "'A' AS outbound_date_type, "
			+ "rq_pattern.num_of_adt AS num_of_adt, "
			+ "rq_pattern.num_of_cnn AS num_of_cnn, "
			+ "rq_pattern.num_of_ins AS num_of_ins, "
			+ "rq_pattern.num_of_inf AS num_of_inf, "
			+ "rq_pattern.stops AS stops, "
			+ "rq_pattern.rbd AS rbd, "
			+ "rq_pattern.exclude_codeshare AS exclude_codeshare, "
			+ "rq_pattern.free_piece AS free_piece "
			+ "FROM "
			+ "rq_pattern "
			+ "UNION ALL "
			+ "SELECT "
			+ "rq_pattern.pattern_id AS pattern_id, "
			+ "rq_pattern.departure_airport AS departure_airport, "
			+ "rq_pattern.arrival_airport AS arrival_airport, "
			+ "rq_pattern.carrier AS carrier, "
			+ "CASE "
			+ "WHEN (outbound_date_to - outbound_date_from) > 180 THEN 181 "
			+ "ELSE rq_pattern.outbound_date_from "
			+ "END AS outbound_date_from, "
			+ "CASE "
			+ "WHEN (outbound_date_to - outbound_date_from) > 180 THEN rq_pattern.outbound_date_to "
			+ "ELSE 180 "
			+ "END AS outbound_date_to, "
			+ "'B' AS outbound_date_type, "
			+ "rq_pattern.num_of_adt AS num_of_adt, "
			+ "rq_pattern.num_of_cnn AS num_of_cnn, "
			+ "rq_pattern.num_of_ins AS num_of_ins, "
			+ "rq_pattern.num_of_inf AS num_of_inf, "
			+ "rq_pattern.stops AS stops, "
			+ "rq_pattern.rbd AS rbd, "
			+ "rq_pattern.exclude_codeshare AS exclude_codeshare, "
			+ "rq_pattern.free_piece AS free_piece "
			+ "FROM "
			+ "rq_pattern "
			+ "WHERE (outbound_date_to - outbound_date_from) > 180) rq_pattern "
			+ "INNER JOIN rq_pattern_staydays ON rq_pattern.pattern_id = rq_pattern_staydays.pattern_id "
			+ "INNER JOIN rq_pattern_cabin ON rq_pattern.pattern_id = rq_pattern_cabin.pattern_id "
			+ "INNER JOIN rq_pattern_outboundtime ON rq_pattern.pattern_id = rq_pattern_outboundtime.pattern_id "
			+ "INNER JOIN rq_pattern_inboundtime ON rq_pattern.pattern_id = rq_pattern_inboundtime.pattern_id "
			+ "ORDER BY outbound_date_type", nativeQuery = true)
	List<CCacheTask> getTasks();
}
